### ISSUE TITLE
macOS Big Sur - Seems to be a problem

### ISSUE THREAD

**Issue by AdamCoulterOz** [aeilot/github-dark-mode-safari#2]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/6822248/99795526-071bc200-2b80-11eb-8347-8d0fafe36e97.png">

**Comment by IMarkoMC** [comment]
Same over here

**Comment by IMarkoMC** [comment]
![image](https://user-images.githubusercontent.com/44303652/99848023-cdcf5c00-2b57-11eb-811a-cc9731d50257.png)

**Comment by aeilot** [comment]
Now I have rebuilt it for Big Sur and the problem is solved. Try [this](https://github.com/aeilot/github-dark-mode-safari/releases/tag/v0.1.3) (GitHubDarkMode-Universal.zip
) out. 

Thank you for creating this issue!

**Comment by IMarkoMC** [comment]
Thanks for the fast update! Trying it now

**Comment by IMarkoMC** [comment]
Mmm I don't know if this is a problem because I did not update my MBP to the latest version but I have the same error 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/44303652/99869521-61317d00-2baa-11eb-924d-dd8e454ed5da.png">

**Comment by aeilot** [comment]
Did you place the extension in the `/Applications` folder? It might be the wrong positon's problem.

**Comment by aeilot** [comment]
`SFErrorDomain error 1.` means `noExtensionFound error.`

**Comment by gitscosh** [comment]
> Did you place the extension in the `/Applications` folder? It might be the wrong positon's problem.

This was exactly the issue. Thank you!

**Comment by IMarkoMC** [comment]
Updated and moved it to /Application and it's working. Thanks for the help
